_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 20
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('fsod-valorant-4-train',)
  TEST: ('fsod-valorant-4-test',)
SOLVER:
  IMS_PER_BATCH: 10
  BASE_LR: 0.001
  STEPS: (35000,)
  MAX_ITER: 40000
  CHECKPOINT_PERIOD: 50000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./faster_rcnn_R_101_FPN_ft_fc_all1_10shot_randnovel"